// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: ohlc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OhlcService_Order_FullMethodName = "/ohlc.OhlcService/Order"
)

// OhlcServiceClient is the client API for OhlcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OhlcServiceClient interface {
	Order(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
}

type ohlcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOhlcServiceClient(cc grpc.ClientConnInterface) OhlcServiceClient {
	return &ohlcServiceClient{cc}
}

func (c *ohlcServiceClient) Order(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, OhlcService_Order_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OhlcServiceServer is the server API for OhlcService service.
// All implementations must embed UnimplementedOhlcServiceServer
// for forward compatibility
type OhlcServiceServer interface {
	Order(context.Context, *OrderRequest) (*OrderResponse, error)
	mustEmbedUnimplementedOhlcServiceServer()
}

// UnimplementedOhlcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOhlcServiceServer struct {
}

func (UnimplementedOhlcServiceServer) Order(context.Context, *OrderRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Order not implemented")
}
func (UnimplementedOhlcServiceServer) mustEmbedUnimplementedOhlcServiceServer() {}

// UnsafeOhlcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OhlcServiceServer will
// result in compilation errors.
type UnsafeOhlcServiceServer interface {
	mustEmbedUnimplementedOhlcServiceServer()
}

func RegisterOhlcServiceServer(s grpc.ServiceRegistrar, srv OhlcServiceServer) {
	s.RegisterService(&OhlcService_ServiceDesc, srv)
}

func _OhlcService_Order_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OhlcServiceServer).Order(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OhlcService_Order_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OhlcServiceServer).Order(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OhlcService_ServiceDesc is the grpc.ServiceDesc for OhlcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OhlcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ohlc.OhlcService",
	HandlerType: (*OhlcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Order",
			Handler:    _OhlcService_Order_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ohlc.proto",
}
